### ISSUE TITLE
copying OcBinaryData files...fatal: not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by startergo** [axivo/opencore#2]
```
python tree.py 
* OpenCore 0.5.8
  - cleaning directory... OK
  - downloading component... OK
  - building files structure... OK
  - installing AppleMCEReporterDisabler... OK
  - copying OcBinaryData files...fatal: not a git repository (or any of the parent directories): .git

Traceback (most recent call last):
  File "/Users/user/Downloads/opencore-master/tree.py", line 150, in <module>
    main(root_directory())
  File "/Users/user/Downloads/opencore-master/tree.py", line 13, in main
    install_opencore('0.5.8', directory)
  File "/Users/user/Downloads/opencore-master/tree.py", line 105, in install_opencore
    check_output(['git', 'submodule', 'update', '--init', '--remote', '--merge'])
  File "/Users/user/.pyenv/versions/2.7.17/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['git', 'submodule', 'update', '--init', '--remote', '--merge']' returned non-zero exit status 128
```

**Comment by fmunteanu** [comment]
You need to either clone or fork the repo, so you set your own configuration, the sample `config.py` contains device properties listed as code examples which will not be compatible with your Mac. I updated the [INSTALL.md](INSTALL.md) documentation.

This is what a first time user will see:
```
$ git clone git@github.com:axivo/opencore.git
Cloning into 'opencore'...
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 20 (delta 0), reused 15 (delta 0), pack-reused 0
Receiving objects: 100% (20/20), 483.52 KiB | 1.67 MiB/s, done.
$ cd opencore
$ python tree.py
* OpenCore 0.5.8
  - downloading component... OK
  - building files structure... OK
  - installing AppleMCEReporterDisabler... OK
  - copying OcBinaryData files...Submodule 'files/OcBinaryData' (https://github.com/acidanthera/OcBinaryData.git) registered for path 'files/OcBinaryData'
Cloning into '/Users/floren/github/opencore/files/OcBinaryData'...
 OK
* Lilu 1.4.4
  - downloading component... OK
  - building files structure... OK
* NightShiftEnabler 1.0.0
  - downloading component... OK
  - building files structure... OK
* WhateverGreen 1.3.9
  - downloading component... OK
  - building files structure... OK
* Miscellaneous
  - fixing file permissions... OK
```

You can also run manually the git submodule commands, as described into [files README](files/README.md).
